### ISSUE TITLE
change default webserver to gunicorn or nginx, etc..

### ISSUE THREAD

**Issue by machow** [datacamp/ast-viewer#11]
@filipsch 

when it was on heroku, I used [this Procfile](https://github.com/datacamp/ast-viewer/blob/de81138ec265148ad781f1d82a73cf9798213745/Procfile) to run the app with gunicorn. However, when moving to elastic beanstalk, I think I left it running with flask's default development server.

Here is the section of the flask docs on deploying with nginx or gunicorn. Happy to help where useful:

http://flask.pocoo.org/docs/1.0/deploying/#self-hosted-options

**Comment by filipsch** [comment]
@machow this is for speed reasons, right? I'll have a look, thanks!

**Comment by filipsch** [comment]
@machow it's using gunicorn now.
