### ISSUE TITLE
Make the implicit explicit: write docs about inner workings

### ISSUE THREAD

**Issue by filipsch** [datacamp/ast-viewer#12]
- Explain `_fields`, `_rules`, how renaming works, how overriding works. (basically the 'syntax' of the fields and rules).
- Simple walkthrough of text -> parsed tree -> shaped tree, so this can be extrapolated to more complex grammars such as tsql and plsql.
- Explain when and why shortcuts were taken, and how they could be resolved in the future.

Deadline that was agreed on: October 1st.

**Comment by hermansje** [comment]
This flow will be documented in the issue referring to this one.
